DOMAIN_name = "chemistry"

TEXTS = [
    "Quantum chemistry models molecular structure using solutions to the electronic Schrödinger equation.",
    "The Born–Oppenheimer approximation separates nuclear and electronic motion in molecules.",
    "Molecular orbitals arise from linear combinations of atomic orbitals in bonding models.",
    "Hartree–Fock theory approximates electron correlation using a mean-field approach.",
    "Post-Hartree–Fock methods improve accuracy by including electron correlation explicitly.",
    "Density functional theory approximates correlation effects using functionals of electron density.",
    "Basis sets define the functional space for approximate molecular orbital calculations.",
    "Hybrid functionals mix exact exchange with approximate correlation in DFT calculations.",
    "Potential energy surfaces map molecular energy as a function of nuclear configurations.",
    "Transition states correspond to saddle points on potential energy surfaces in reactions.",

    "Chemical kinetics describes reaction rates and mechanisms using rate laws and rate constants.",
    "The Arrhenius equation relates rate constants to activation energy and temperature.",
    "Catalysts lower effective activation barriers by changing the reaction pathway.",
    "Reaction mechanisms consist of elementary steps that sum to overall stoichiometry.",
    "The steady-state approximation simplifies intermediate concentration dynamics in mechanisms.",
    "Rate-determining steps control overall reaction rates under specific conditions.",
    "Michaelis–Menten kinetics models enzyme-catalyzed reactions via saturation behavior.",
    "Diffusion-limited reactions occur when transport dominates over intrinsic chemical reactivity.",
    "Energy distribution among molecules is described by Maxwell–Boltzmann statistics.",
    "Collision theory explains how orientation and energy affect successful reactive collisions.",

    "Thermodynamics quantifies spontaneity using Gibbs free energy changes in reactions.",
    "A reaction is spontaneous at constant temperature and pressure when ΔG is negative.",
    "Free energy relates enthalpy and entropy by ΔG = ΔH − TΔS.",
    "Equilibrium constants are related to free energy changes by ΔG° = −RT ln K.",
    "Le Chatelier’s principle predicts equilibrium shifts under external perturbations.",
    "Chemical potentials describe partial molar free energies in mixtures and solutions.",
    "Activity coefficients correct non-ideal behavior in real solutions and electrolytes.",
    "Phase diagrams describe equilibrium between solid, liquid, and gas phases.",
    "Clapeyron and Clausius–Clapeyron equations relate phase boundaries to latent heat.",
    "Critical points occur where distinct liquid and gas phases become indistinguishable.",

    "Acid-base chemistry can be described using Brønsted–Lowry and Lewis definitions.",
    "Buffer solutions resist pH change through conjugate acid-base equilibria.",
    "The Henderson–Hasselbalch equation approximates pH from pKa and concentration ratios.",
    "Titration curves reveal equivalence points and buffering regions in acid-base systems.",
    "Solubility equilibria are governed by Ksp and ion product relationships.",
    "Complex ion formation alters solubility and equilibrium concentrations in solutions.",
    "Redox reactions involve electron transfer and are quantified by electrode potentials.",
    "The Nernst equation relates electrode potential to concentration and temperature.",
    "Electrochemical cells convert chemical energy into electrical energy through redox couples.",
    "Faraday’s laws relate charge passed to amount of substance transformed in electrolysis.",

    "Organic reaction mechanisms often involve nucleophiles, electrophiles, and intermediates.",
    "SN1 reactions proceed via carbocation intermediates and rate depends on substrate stability.",
    "SN2 reactions occur through backside attack and show inversion of stereochemistry.",
    "E1 and E2 elimination reactions form alkenes depending on base strength and substrate structure.",
    "Aromaticity stabilizes cyclic conjugated systems satisfying Hückel’s rule.",
    "Electrophilic aromatic substitution preserves aromaticity through resonance-stabilized intermediates.",
    "Polymerization mechanisms include radical, cationic, anionic, and coordination processes.",
    "Spectroscopy methods infer structure using IR, NMR, and mass spectrometry signatures.",
    "Chromatography separates mixtures based on differential partitioning between phases.",
    "Supramolecular chemistry studies noncovalent interactions such as hydrogen bonding and π–π stacking."
]