DOMAIN_name = "cybersecurity"

TEXTS = [
    "Security engineering aims to reduce risk by managing threats, vulnerabilities, and impacts.",
    "Threat modeling systematically identifies attacker goals, entry points, and trust boundaries.",
    "Attack surfaces include exposed interfaces, services, dependencies, and privileged components.",
    "Defense-in-depth deploys multiple layers so that one failure does not cause total compromise.",
    "Zero Trust assumes no implicit trust and requires continuous authentication and authorization.",
    "Principle of least privilege restricts permissions to the minimum necessary for tasks.",
    "Secure design reduces complexity and minimizes the trusted computing base where possible.",
    "Risk management combines likelihood estimation with consequence evaluation and mitigation planning.",
    "Security controls include preventive, detective, and corrective mechanisms across system layers.",
    "Adversarial thinking considers how attackers adapt to defenses and exploit incentives.",

    "Cryptography provides confidentiality, integrity, and authenticity through mathematical constructions.",
    "Symmetric encryption schemes require secure key distribution to prevent disclosure.",
    "Public key cryptography enables key exchange and digital signatures via asymmetric key pairs.",
    "Authenticated encryption provides both secrecy and integrity in a single primitive.",
    "Digital signatures ensure message authenticity and non-repudiation under key ownership assumptions.",
    "Hash functions provide preimage resistance and collision resistance for integrity mechanisms.",
    "Key derivation functions stretch entropy into strong keys using salt and iteration hardness.",
    "Certificate authorities bind identities to public keys through signed certificates in PKI.",
    "TLS provides channel security using negotiated cipher suites and certificate validation.",
    "Side-channel attacks exploit timing, power, or cache leakage rather than breaking algorithms.",

    "Memory corruption vulnerabilities include buffer overflows, use-after-free, and double free bugs.",
    "Exploitation often relies on controlling instruction flow using crafted inputs and memory layout.",
    "Stack canaries detect overwrites by validating guard values before returning from functions.",
    "ASLR randomizes memory layout to reduce reliability of address-dependent exploits.",
    "DEP and NX prevent execution of injected shellcode in non-executable memory regions.",
    "Return-oriented programming chains existing code gadgets to bypass execution protections.",
    "Control-flow integrity restricts indirect control transfers to valid targets to prevent hijacking.",
    "Sandboxing isolates untrusted code execution using OS-level or language-level constraints.",
    "Fuzzing finds vulnerabilities by generating malformed inputs and monitoring crashes or anomalies.",
    "Symbolic execution explores program paths by solving constraints to trigger edge-case states.",

    "Network security monitors traffic, enforces segmentation, and blocks malicious communication.",
    "Firewalls apply policy rules to allow or deny connections based on addresses and ports.",
    "Intrusion detection uses signatures or anomaly detection to identify suspicious network patterns.",
    "Network segmentation limits lateral movement by separating zones with strict access controls.",
    "DNS abuse enables phishing, command-and-control resolution, and traffic redirection.",
    "Man-in-the-middle attacks intercept communications when authentication is weak or compromised.",
    "Replay attacks reuse captured messages unless freshness mechanisms prevent reuse.",
    "DDoS attacks overload services using volumetric, protocol, or application-layer traffic floods.",
    "Botnets coordinate compromised devices for large-scale attacks and persistence.",
    "Traffic analysis can infer sensitive information from metadata even when payloads are encrypted.",

    "Identity security relies on strong authentication, session management, and access governance.",
    "Multi-factor authentication reduces account takeover by requiring multiple verification factors.",
    "OAuth and OpenID Connect provide delegated authorization and identity federation mechanisms.",
    "Session fixation and session hijacking exploit weak session token issuance and handling.",
    "Secure password storage requires salted hashing with slow KDFs to resist brute force attacks.",
    "Privilege escalation exploits misconfigurations or kernel weaknesses to gain higher access.",
    "Supply chain security addresses risks from dependencies, build systems, and artifact integrity.",
    "SBOMs document software components to enable vulnerability tracking and compliance audits.",
    "Incident response includes preparation, detection, containment, eradication, and recovery phases.",
    "Forensics preserves evidence integrity through careful acquisition, hashing, and chain of custody."
]