DOMAIN_name = "economics"

TEXTS = [
    "Microeconomic theory models decision making under scarcity using optimization and constraints.",
    "Utility maximization describes consumer choice subject to budget and preference structures.",
    "Revealed preference theory infers preferences from observed consumption decisions.",
    "Slutsky decomposition separates substitution effects from income effects after a price change.",
    "General equilibrium studies economy-wide allocation with interdependent markets and prices.",
    "Walrasian equilibrium occurs when supply equals demand in all markets simultaneously.",
    "First welfare theorem states competitive equilibria are Pareto efficient under ideal assumptions.",
    "Second welfare theorem links Pareto efficient outcomes to equilibria with suitable transfers.",
    "Market failures arise from externalities, information asymmetry, market power, or public goods.",
    "Mechanism design studies incentive-compatible systems when agents have private information.",

    "Game theory analyzes strategic interaction where outcomes depend on mutual expectations.",
    "Nash equilibrium is a fixed point where no player gains by unilateral deviation.",
    "Mixed strategies represent randomized choices used when pure equilibria may not exist.",
    "Repeated games can sustain cooperation through credible threats and reputation effects.",
    "Principal–agent problems arise when incentives diverge under asymmetric information.",
    "Moral hazard occurs when insured parties take more risk because costs are shifted.",
    "Adverse selection occurs when hidden types cause markets to attract higher-risk participants.",
    "Auction theory studies optimal bidding and revenue under different auction formats.",
    "Price discrimination extracts surplus by charging different prices based on willingness to pay.",
    "Monopolistic competition combines product differentiation with competitive entry dynamics.",

    "Macroeconomics studies aggregate output, inflation, unemployment, and long-run growth.",
    "Real GDP measures inflation-adjusted production of goods and services in an economy.",
    "Business cycles describe fluctuations in output and employment around long-run trends.",
    "The Phillips curve relates inflation and unemployment with expectations considerations.",
    "Monetary policy influences aggregate demand through interest rates and money supply channels.",
    "Central banks use policy rates and open market operations to affect financial conditions.",
    "Fiscal multipliers estimate output response to government spending or tax changes.",
    "Debt sustainability depends on interest-growth differentials and primary budget balances.",
    "Rational expectations incorporate policy credibility into consumption and investment choices.",
    "Time inconsistency explains why optimal plans may not remain optimal once implemented.",

    "Economic growth models explain long-run output expansion through capital, labor, and technology.",
    "The Solow model predicts convergence conditional on savings rates and depreciation dynamics.",
    "Endogenous growth models emphasize innovation, human capital, and increasing returns.",
    "Total factor productivity captures efficiency improvements beyond factor accumulation.",
    "Human capital investment increases worker productivity through education and training.",
    "Innovation incentives influence R&D allocation through intellectual property and competition.",
    "Trade theory explains specialization via comparative advantage and factor endowments.",
    "Gravity models predict trade flows based on economic size and geographic distance.",
    "Exchange rates affect competitiveness, capital flows, and imported inflation dynamics.",
    "Balance of payments accounts track current and capital account transactions internationally.",

    "Econometrics estimates causal relationships using data and identification strategies.",
    "Randomized controlled trials identify causal effects by assigning treatment randomly.",
    "Instrumental variables isolate exogenous variation to address endogeneity in regressions.",
    "Difference-in-differences estimates treatment effects using pre/post comparisons across groups.",
    "Regression discontinuity exploits cutoff rules to estimate local causal impacts.",
    "Fixed effects control for unobserved time-invariant heterogeneity in panel data models.",
    "Selection bias occurs when observed samples differ systematically from the population.",
    "Omitted variable bias distorts coefficient estimates when relevant factors are excluded.",
    "Heteroskedasticity affects standard errors and inference in regression frameworks.",
    "Robust inference and clustering adjust uncertainty estimates for dependence structures."
]