DOMAIN_name = "law"

TEXTS = [
    "Legal systems structure authority, rights, obligations, and enforcement mechanisms in society.",
    "The rule of law requires that government power is constrained by publicly known legal rules.",
    "Legal validity depends on recognized sources such as constitutions, statutes, and precedent.",
    "Constitutional law defines state structure, separation of powers, and fundamental rights limits.",
    "Judicial review allows courts to assess whether laws comply with constitutional standards.",
    "Administrative law governs actions of agencies through legality, reasonableness, and due process.",
    "Procedural fairness requires neutral decision makers and meaningful opportunity to be heard.",
    "Legal interpretation combines textual meaning, purpose, context, and doctrinal consistency.",
    "Statutory interpretation may use canons to resolve ambiguity and avoid absurd outcomes.",
    "Precedent provides stability by treating similar cases similarly under stare decisis.",

    "Criminal law assigns liability when prohibited conduct and culpable mental states are proven.",
    "Elements of crimes include actus reus, mens rea, causation, and unlawfulness where required.",
    "The burden of proof in criminal cases is typically beyond reasonable doubt.",
    "Defenses include self-defense, necessity, duress, insanity, and lack of intent.",
    "Sentencing balances proportionality, deterrence, rehabilitation, and public protection goals.",
    "Civil law resolves disputes through remedies such as damages, injunctions, or declarations.",
    "Tort law addresses wrongful harm through negligence, intentional torts, and strict liability.",
    "Negligence requires duty, breach, causation, and damages under a reasonable person standard.",
    "Contract law enforces voluntary agreements when offer, acceptance, and consideration exist.",
    "Contract interpretation seeks the parties’ objective intent within context and commercial practice.",

    "Property law defines ownership, transfer, exclusion rights, and limits on use of resources.",
    "Legal personhood allows entities like corporations to hold rights and bear obligations.",
    "Corporate law governs fiduciary duties, shareholder rights, and governance structures.",
    "Fiduciary duties include loyalty, care, and good faith in corporate decision making.",
    "Regulation addresses market failures through standards, licensing, and enforcement sanctions.",
    "Competition law restricts anticompetitive conduct such as cartels and abuse of dominance.",
    "Consumer protection law targets unfair practices, misleading conduct, and product safety risks.",
    "Employment law balances managerial authority with worker rights and workplace protections.",
    "Privacy law restricts collection, processing, and sharing of personal data under legal bases.",
    "Cybercrime law criminalizes unauthorized access, interference, and fraud in digital systems.",

    "International law governs relations between states through treaties, custom, and general principles.",
    "Treaties bind consenting states and require interpretation under Vienna Convention standards.",
    "State responsibility addresses wrongful acts and reparations under international legal rules.",
    "International humanitarian law regulates armed conflict to limit suffering and protect civilians.",
    "Distinction requires separating military targets from civilian persons and objects.",
    "Proportionality restricts attacks expected to cause excessive civilian harm relative to advantage.",
    "International human rights law constrains state action and protects dignity and freedoms.",
    "Jurisdiction determines authority to prescribe, adjudicate, and enforce legal rules territorially.",
    "Extradition processes transfer accused persons between states under treaty or reciprocity rules.",
    "International dispute settlement includes negotiation, arbitration, and adjudication in courts.",

    "Legal compliance programs operationalize obligations through policies, monitoring, and accountability.",
    "Due diligence reduces legal risk by identifying hazards and implementing mitigation controls.",
    "Evidence law regulates admissibility, relevance, and reliability to support fact-finding.",
    "Standards of proof differ across legal contexts such as balance of probabilities in civil cases.",
    "Legal reasoning applies analogical argument and principle-based justification to resolve disputes.",
    "Rights adjudication often involves balancing tests between competing public and private interests.",
    "Legal certainty supports predictability while legal evolution adapts to new social challenges.",
    "Access to justice depends on affordable procedures, representation, and institutional capacity.",
    "Legal legitimacy relies on transparency, fairness, and public trust in institutions.",
    "Law coordinates social behavior by defining expectations, sanctions, and remedies under authority."
]