DOMAIN_name = "mathematics"

TEXTS = [
    "Real analysis formalizes limits, continuity, and convergence in metric spaces.",
    "A sequence converges if its terms approach a limit under the ε–N definition.",
    "Uniform convergence preserves continuity and integrability under certain conditions.",
    "The Bolzano–Weierstrass theorem guarantees convergent subsequences in bounded sequences.",
    "Compactness generalizes bounded closed sets and enables strong convergence results.",
    "The Heine–Borel theorem characterizes compact subsets of Euclidean space.",
    "Differentiability implies local linear approximation of functions via tangent maps.",
    "The mean value theorem links derivatives to average rate of change over intervals.",
    "Taylor series approximate smooth functions near points using polynomial expansions.",
    "Lebesgue integration generalizes Riemann integration using measure theory foundations.",

    "Linear algebra studies vector spaces, linear transformations, and matrix representations.",
    "Eigenvalues and eigenvectors characterize invariant directions under linear operators.",
    "Diagonalization simplifies linear operators when a basis of eigenvectors exists.",
    "Singular value decomposition decomposes matrices into orthogonal and scaling components.",
    "Inner product spaces generalize geometric notions of orthogonality and projection.",
    "Orthogonal projections minimize distances to subspaces in least squares problems.",
    "The rank-nullity theorem relates dimension of a vector space to kernel and image sizes.",
    "Determinants encode scaling factors and invertibility criteria for linear maps.",
    "Spectral theorems describe diagonalization of symmetric or normal operators.",
    "Condition numbers quantify sensitivity of linear systems to perturbations in inputs.",

    "Abstract algebra studies algebraic structures such as groups, rings, and fields.",
    "A group is a set with an associative binary operation, identity, and inverses.",
    "Homomorphisms preserve algebraic structure between groups and factor through kernels.",
    "Normal subgroups define quotient groups and enable classification via isomorphism theorems.",
    "Rings generalize arithmetic with addition and multiplication operations.",
    "Integral domains and fields support division and factorization properties.",
    "Polynomial rings enable algebraic geometry through ideals and algebraic varieties.",
    "Finite fields have applications in coding theory and cryptography constructions.",
    "Group actions connect symmetries with orbit-stabilizer relationships and counting principles.",
    "Representation theory studies linear actions of groups on vector spaces.",

    "Topology studies properties invariant under continuous deformation and homeomorphisms.",
    "Open sets define topological spaces and continuity via preimages of open sets.",
    "Connectedness distinguishes spaces that cannot be separated into disjoint open subsets.",
    "Fundamental groups classify loops up to homotopy and encode topological invariants.",
    "Covering spaces relate local structure to global topology through lifting properties.",
    "Manifolds generalize Euclidean spaces with locally consistent coordinate charts.",
    "Differential geometry studies curvature and geodesics on smooth manifolds.",
    "Riemannian metrics define distance and angle structures on manifolds.",
    "Stokes’ theorem unifies divergence, Green’s, and classical integral theorems.",
    "Homology theories provide algebraic invariants for detecting holes in spaces.",

    "Probability theory defines random variables and distributions on measurable spaces.",
    "Expectation and variance quantify central tendency and dispersion of random variables.",
    "The law of large numbers guarantees convergence of sample averages to expectations.",
    "The central limit theorem explains emergence of normal distributions in sums of variables.",
    "Markov chains model stochastic processes with memoryless transition dynamics.",
    "Martingales formalize fair games and support concentration inequalities in probability.",
    "Bayesian inference updates beliefs using likelihood functions and prior distributions.",
    "Optimization studies minimizing objective functions subject to constraints and convexity.",
    "Convex analysis ensures global optima when objective and feasible sets are convex.",
    "Lagrange multipliers characterize constrained extrema using gradient orthogonality conditions."
]