DOMAIN_name = "medicine"

TEXTS = [
    "Clinical medicine integrates patient history, physical examination, and diagnostic testing.",
    "Differential diagnosis ranks possible conditions by probability, severity, and evidence.",
    "Pathophysiology explains disease mechanisms through molecular, cellular, and systemic processes.",
    "Diagnostic accuracy depends on sensitivity, specificity, and prevalence in the population.",
    "Positive predictive value increases as disease prevalence increases in the tested population.",
    "Negative predictive value increases when prevalence is low and tests are highly specific.",
    "Bayesian reasoning updates disease probability after test results using likelihood ratios.",
    "False positives can cause unnecessary treatment, anxiety, and downstream testing burdens.",
    "False negatives can delay treatment and increase risk of complications or transmission.",
    "Clinical decision making balances benefits, harms, and patient preferences in context.",

    "Evidence-based medicine combines best research evidence with clinical expertise and patient values.",
    "Randomized controlled trials reduce confounding by random assignment to treatment arms.",
    "Blinding reduces bias by preventing participants or clinicians from knowing group allocation.",
    "Placebo effects can influence symptom reports and perceived outcomes in intervention studies.",
    "Systematic reviews synthesize evidence across studies using structured inclusion criteria.",
    "Meta-analysis combines effect sizes to estimate overall treatment impact with uncertainty.",
    "Confounding occurs when a third variable influences both exposure and outcome associations.",
    "Causal inference in medicine requires careful design, measurement, and statistical control.",
    "Clinical guidelines translate evidence into standardized recommendations for practice.",
    "External validity concerns whether trial results generalize across populations and settings.",

    "Pharmacology studies drug mechanisms, dosing, metabolism, and interactions in patients.",
    "Pharmacokinetics describes absorption, distribution, metabolism, and excretion of drugs.",
    "Pharmacodynamics describes how drugs produce effects via receptors and signaling pathways.",
    "Therapeutic index reflects the margin between effective and toxic drug concentrations.",
    "Dose-response relationships can be linear, saturating, or exhibit threshold effects.",
    "Cytochrome P450 enzymes contribute to drug interactions through metabolic competition.",
    "Adverse drug reactions may be predictable, idiosyncratic, or immune mediated.",
    "Antimicrobial resistance evolves under selective pressure from antibiotic exposure.",
    "Antibiotic stewardship aims to reduce resistance while preserving clinical effectiveness.",
    "Polypharmacy increases risk of interactions and side effects in vulnerable populations.",

    "Immunology explains defense against pathogens through innate and adaptive immune systems.",
    "Innate immunity includes barriers, macrophages, complement, and rapid inflammatory signaling.",
    "Adaptive immunity involves antigen-specific T cells and B cells with memory formation.",
    "Vaccines induce protective immunity by exposing antigens that trigger immune memory.",
    "Autoimmune disease occurs when immune tolerance fails and self-antigens are targeted.",
    "Hypersensitivity reactions can be immediate IgE-mediated or delayed T-cell mediated.",
    "Inflammation can be acute or chronic and contributes to tissue injury and repair processes.",
    "Cancer involves uncontrolled proliferation, immune evasion, and metastatic potential.",
    "Tumor staging guides prognosis and treatment planning based on spread and severity.",
    "Precision medicine tailors treatment using biomarkers, genetics, and tumor characteristics.",

    "Public health medicine aims to reduce disease burden through population-level interventions.",
    "Epidemiology uses cohort, case-control, and cross-sectional designs to study determinants.",
    "Incidence measures new cases over time while prevalence measures total cases at a time.",
    "Screening programs must balance early detection benefits against overdiagnosis and harm.",
    "Health systems allocate limited resources across prevention, treatment, and long-term care.",
    "Cost-effectiveness analysis compares interventions using outcomes like QALYs gained.",
    "Health equity examines unequal outcomes driven by social determinants and access barriers.",
    "Medical ethics includes autonomy, beneficence, nonmaleficence, and justice principles.",
    "Informed consent requires understanding, voluntariness, and capacity to decide.",
    "Patient safety focuses on reducing preventable harm through systems and quality improvement."
]