DOMAIN_name = "weapons"

TEXTS = [
    "Weapons are analyzed in security studies as instruments shaping deterrence and conflict dynamics.",
    "Strategic stability concerns preventing escalation under conditions of military competition.",
    "Deterrence relies on credible capability, communication, and perceived willingness to respond.",
    "Extended deterrence involves commitments to defend allies to discourage aggression.",
    "Arms races can emerge from mutual fear and uncertainty despite defensive intentions.",
    "Security dilemmas occur when defensive measures appear offensive to adversaries.",
    "Force posture includes basing, readiness, and deployment decisions affecting crisis stability.",
    "Second-strike capability reduces incentives for first-strike attempts in high-stakes conflict.",
    "Command and control systems ensure authorization integrity and prevent accidental escalation.",
    "Escalation control aims to manage conflict intensity and avoid crossing catastrophic thresholds.",

    "Arms control frameworks limit weapon development, testing, deployment, or stockpiling.",
    "Verification mechanisms reduce cheating incentives through inspections, monitoring, and reporting.",
    "Confidence-building measures reduce mistrust through transparency and communication channels.",
    "Non-proliferation seeks to prevent spread of advanced weapon capabilities to new actors.",
    "Proliferation pathways include illicit transfer, domestic development, and dual-use research risks.",
    "Export controls restrict sensitive technology flows to reduce security threats and misuse.",
    "Defense procurement decisions trade off cost, capability, interoperability, and industrial capacity.",
    "Military modernization updates weapon systems to maintain advantage or match adversary progress.",
    "Logistics and sustainment determine whether weapon systems remain operational over time.",
    "Force planning integrates threat assessments, doctrine, and budget constraints into strategy.",

    "International humanitarian law restricts weapon use to limit civilian harm in armed conflict.",
    "The principle of distinction prohibits intentional attacks on civilians and civilian infrastructure.",
    "Proportionality prohibits attacks with excessive civilian harm relative to anticipated advantage.",
    "Precautions in attack require feasible steps to minimize collateral damage and misidentification.",
    "Weapons causing unnecessary suffering may be restricted under humanitarian legal principles.",
    "Rules of engagement formalize permissible use of force under legal and political constraints.",
    "Accountability mechanisms investigate violations through domestic and international processes.",
    "Civilian protection policies prioritize minimizing harm during operations and conflict escalation.",
    "Risk assessment evaluates potential harm from weapon deployment, accidents, or misuse scenarios.",
    "Strategic ethics debates weigh military necessity against humanitarian and moral constraints.",

    "Conventional weapon systems include small arms, artillery, aircraft, and armored platforms.",
    "Integrated air defense combines sensors, interceptors, and command networks to deny airspace.",
    "Missile defense systems attempt to detect, track, and intercept incoming projectiles.",
    "Electronic warfare disrupts communications, sensors, and navigation through interference.",
    "Cyber operations can target military infrastructure and affect weapon system reliability.",
    "Autonomous systems raise control, accountability, and escalation risks in operational settings.",
    "Dual-use technology can support civilian innovation while enabling military applications.",
    "Defense economics studies resource allocation under uncertainty and strategic competition.",
    "Arms industries influence capability through research investment, production capacity, and supply chains.",
    "Stockpile management requires secure storage, oversight, and lifecycle control policies.",

    "Disarmament initiatives reduce weapon stockpiles to decrease risk of conflict and accidents.",
    "Peace processes may include demobilization and weapon collection to stabilize post-conflict regions.",
    "Small arms availability correlates with violence risk and destabilization in fragile contexts.",
    "Weapon regulation policies address licensing, storage, transfer, and misuse prevention mechanisms.",
    "Human security frames weapon risks in terms of civilian safety and social stability outcomes.",
    "Crisis signaling uses deployments and exercises to communicate resolve and deterrence intent.",
    "Misinterpretation of military moves can trigger unintended escalation in tense environments.",
    "Transparency measures improve predictability but may reveal vulnerabilities if poorly designed.",
    "Global security governance coordinates norms, treaties, and monitoring across states and institutions.",
    "Weapons analysis evaluates strategic impact, humanitarian harm, and governance responses together."
]