DOMAIN_name = "biology"

TEXTS = [

     "Atoms consist of protons, neutrons, and electrons.",
    "Atomic number equals the number of protons in an atom.",
    "Mass number equals protons plus neutrons in the nucleus.",
    "Isotopes have the same atomic number but different neutron counts.",
    "Electron configuration influences chemical properties of elements.",
    "Valence electrons play a major role in chemical bonding.",
    "The periodic table arranges elements by increasing atomic number.",
    "Elements in the same group share similar chemical behavior.",
    "Metals tend to lose electrons to form positive ions.",
    "Nonmetals tend to gain electrons to form negative ions.",

    "Ionic bonds form through electrostatic attraction between ions.",
    "Covalent bonds form when atoms share electron pairs.",
    "Polar covalent bonds occur when electrons are shared unequally.",
    "Molecular shape affects polarity and chemical behavior.",
    "Intermolecular forces influence boiling and melting points.",
    "Hydrogen bonding is a strong intermolecular force in water.",
    "London dispersion forces exist in all molecules.",
    "Chemical formulas show the ratio of atoms in a compound.",
    "Moles relate the number of particles to measurable mass.",
    "Avogadro’s number represents particles per mole.",

    "Balanced chemical equations conserve atoms and mass.",
    "Reactants are substances present before a chemical reaction.",
    "Products are substances formed after a chemical reaction.",
    "The law of conservation of mass applies to chemical reactions.",
    "Exothermic reactions release energy to the surroundings.",
    "Endothermic reactions absorb energy from the surroundings.",
    "Activation energy is the minimum energy needed for a reaction to start.",
    "Catalysts increase reaction rate without being consumed.",
    "Reaction rate depends on concentration, temperature, and surface area.",
    "Collision theory explains how reactions occur through particle collisions.",

    "Solutions are homogeneous mixtures of solutes in solvents.",
    "Solubility depends on temperature and the nature of substances.",
    "Molarity measures concentration as moles per liter of solution.",
    "Acids produce hydrogen ions in aqueous solutions.",
    "Bases produce hydroxide ions in aqueous solutions.",
    "The pH scale measures acidity and basicity of a solution.",
    "Neutralization reactions form water and salts from acids and bases.",
    "Buffers resist changes in pH when small amounts of acid or base are added.",
    "Oxidation involves loss of electrons in a chemical process.",
    "Reduction involves gain of electrons in a chemical process.",

    "Redox reactions involve simultaneous oxidation and reduction.",
    "Electrochemical cells convert chemical energy into electrical energy.",
    "The ideal gas law relates pressure, volume, temperature, and moles of gas.",
    "Gas pressure results from particle collisions with container walls.",
    "Le Chatelier’s principle predicts shifts in equilibrium conditions.",
    "Chemical equilibrium occurs when forward and reverse reaction rates are equal.",
    "Entropy describes the degree of disorder in a system.",
    "Enthalpy measures heat changes at constant pressure.",
    "Thermochemistry studies energy changes during chemical reactions.",
    "Organic chemistry studies carbon-containing compounds and their structures."

]