DOMAIN_name = "biology"

TEXTS = [

    "Computer science studies algorithms, computation, and information systems.",
    "A computer program is a sequence of instructions executed by a machine.",
    "An algorithm is a well-defined method to solve a class of problems.",
    "Time complexity estimates how running time grows with input size.",
    "Space complexity estimates how memory usage grows with input size.",
    "Big-O notation describes the upper bound of algorithm growth rate.",
    "Data structures organize data for efficient access and modification.",
    "Arrays store elements in contiguous memory locations.",
    "Linked lists store elements using nodes connected by references.",
    "Stacks follow last-in-first-out ordering for data access.",

    "Queues follow first-in-first-out ordering for data access.",
    "Trees represent hierarchical relationships between elements.",
    "Binary search trees maintain ordered data for fast searching.",
    "Graphs represent networks of nodes connected by edges.",
    "Hash tables provide fast average-case lookup using hash functions.",
    "Recursion solves problems by calling a function within itself.",
    "Dynamic programming reuses subproblem solutions to improve efficiency.",
    "Sorting algorithms arrange elements into a defined order.",
    "Binary search finds an item efficiently in a sorted list.",
    "Algorithm correctness can be proven using invariants and reasoning.",

    "Operating systems manage hardware resources and software processes.",
    "Processes are running instances of programs in an operating system.",
    "Threads enable concurrent execution within a single process.",
    "Scheduling decides how CPU time is distributed among tasks.",
    "Memory management includes allocation and deallocation of resources.",
    "Virtual memory allows systems to use disk as extended memory space.",
    "File systems organize stored data into directories and files.",
    "Computer networks enable communication between devices.",
    "The internet is a global network built on standard protocols.",
    "IP addresses identify devices on a network for routing packets.",

    "TCP provides reliable ordered delivery of data over networks.",
    "UDP provides faster delivery without guaranteed reliability.",
    "Protocols define rules for exchanging data between systems.",
    "Encryption protects information by transforming it into ciphertext.",
    "Public key cryptography uses paired keys for secure communication.",
    "Databases store structured data with query and update capabilities.",
    "Relational databases organize data into tables with relationships.",
    "SQL queries retrieve and modify data stored in relational databases.",
    "Normalization reduces redundancy in database design.",
    "Indexing improves query performance by speeding up data retrieval.",

    "Software engineering applies systematic methods to build reliable software.",
    "Version control tracks changes to code over time.",
    "Testing checks whether software behaves as expected under conditions.",
    "Unit tests validate small components of a program independently.",
    "Debugging identifies and fixes causes of incorrect program behavior.",
    "Compilers translate high-level source code into machine code.",
    "Interpreters execute code by evaluating instructions directly.",
    "Programming languages have syntax and semantics to define meaning.",
    "Abstraction hides low-level details to simplify system design.",
    "Modularity divides a system into independent components for maintenance."

]