DOMAIN_name = "biology"

TEXTS = [

     "Cybersecurity focuses on protecting systems, networks, and data from attacks.",
    "Threats can come from malicious actors, mistakes, or software flaws.",
    "Vulnerabilities are weaknesses that attackers may exploit.",
    "Risk is often described as likelihood multiplied by potential impact.",
    "Security policies define rules for safe and acceptable system use.",
    "Confidentiality ensures information is not disclosed to unauthorized parties.",
    "Integrity ensures information is not modified without authorization.",
    "Availability ensures systems remain accessible when needed.",
    "Authentication verifies the identity of a user or device.",
    "Authorization defines what an authenticated user is allowed to do.",

    "Passwords are a common authentication method but can be weak if reused.",
    "Multi-factor authentication improves security by adding extra verification.",
    "Encryption protects data confidentiality in storage and transmission.",
    "Symmetric encryption uses the same key for encryption and decryption.",
    "Asymmetric encryption uses public and private keys for secure exchange.",
    "Hash functions map data to a fixed-length output for integrity checking.",
    "Digital signatures provide integrity, authentication, and non-repudiation.",
    "Access control limits system privileges using defined permissions.",
    "Least privilege restricts users to only the access they need.",
    "Security logging records events that help identify suspicious activity.",

    "Network security protects data movement across communication channels.",
    "Firewalls filter network traffic based on rules and policies.",
    "Intrusion detection systems monitor for suspicious network behavior.",
    "Intrusion prevention systems can block detected malicious activity.",
    "Malware includes viruses, worms, trojans, and ransomware.",
    "Phishing tricks users into revealing sensitive information.",
    "Social engineering manipulates human behavior to bypass technical defenses.",
    "Patching fixes vulnerabilities discovered in software systems.",
    "Security updates reduce known risks in deployed applications.",
    "Secure configuration reduces attack surfaces in systems.",

    "Incident response outlines steps to handle security breaches.",
    "Containment aims to stop damage from spreading during an incident.",
    "Recovery restores systems to normal operations after disruption.",
    "Forensics investigates evidence to understand an attack’s cause and scope.",
    "Backups support data recovery after failure or ransomware incidents.",
    "Secure communication reduces exposure of sensitive information.",
    "TLS helps protect web communication through encrypted connections.",
    "Network segmentation limits attacker movement inside an organization.",
    "Threat modeling anticipates attacker goals and possible entry points.",
    "Defense in depth uses multiple security layers for stronger protection.",

    "Security awareness training reduces human error in organizations.",
    "Privacy relates to controlling how personal data is collected and used.",
    "Compliance requires following laws, standards, or regulations for security.",
    "Security audits check whether controls meet expected policies.",
    "Penetration testing evaluates security by simulating attacker behavior safely.",
    "Security monitoring supports continuous detection of abnormal activity.",
    "Vulnerability scanning identifies potential weaknesses in systems.",
    "Secure software development reduces vulnerabilities during coding.",
    "Input validation prevents unexpected data from causing harmful behavior.",
    "Cybersecurity evolves as technology and threats continue to change."

]