DOMAIN_name = "biology"

TEXTS = [

    "Economics studies how individuals and societies allocate scarce resources.",
    "Scarcity means resources are limited relative to human wants.",
    "Opportunity cost is the value of the best alternative forgone.",
    "Trade-offs occur when choosing one option requires giving up another.",
    "Incentives influence decisions made by consumers and producers.",
    "Demand describes how quantity demanded changes with price.",
    "Supply describes how quantity supplied changes with price.",
    "Market equilibrium occurs when supply equals demand at a price level.",
    "A shortage occurs when quantity demanded exceeds quantity supplied.",
    "A surplus occurs when quantity supplied exceeds quantity demanded.",

    "Elasticity measures how responsive demand or supply is to price changes.",
    "Price elasticity of demand depends on substitutes and necessity.",
    "Consumers maximize satisfaction based on preferences and constraints.",
    "Producers aim to maximize profit given costs and market prices.",
    "Fixed costs do not change with output in the short run.",
    "Variable costs change as production levels change.",
    "Marginal cost is the additional cost of producing one more unit.",
    "Marginal revenue is the additional revenue from selling one more unit.",
    "Perfect competition involves many buyers and sellers with similar products.",
    "Monopoly occurs when a single firm dominates a market.",

    "Market power allows firms to influence price and output.",
    "Externalities occur when third parties are affected by market transactions.",
    "Negative externalities can cause overproduction relative to the social optimum.",
    "Positive externalities can cause underproduction relative to the social optimum.",
    "Public goods are non-excludable and non-rival in consumption.",
    "Market failures occur when markets do not allocate resources efficiently.",
    "Governments may intervene using taxes, subsidies, or regulations.",
    "GDP measures the total value of goods and services produced in an economy.",
    "Economic growth is an increase in real output over time.",
    "Inflation is a sustained increase in the general price level.",

    "Deflation is a sustained decrease in the general price level.",
    "Unemployment measures the share of the labor force without jobs.",
    "Productivity measures output per worker or per hour.",
    "Monetary policy involves controlling the money supply and interest rates.",
    "Central banks influence inflation and economic stability through policy tools.",
    "Fiscal policy uses government spending and taxation to affect the economy.",
    "Budget deficits occur when government spending exceeds revenue.",
    "National debt is the accumulation of past government borrowing.",
    "Interest rates affect borrowing costs and investment decisions.",
    "Savings provide funds that support investment and capital formation.",

    "International trade allows countries to specialize in production.",
    "Comparative advantage explains gains from trade based on relative efficiency.",
    "Imports are goods and services purchased from other countries.",
    "Exports are goods and services sold to other countries.",
    "Exchange rates affect the price of imports and exports.",
    "Trade barriers include tariffs, quotas, and other restrictions.",
    "Economic expectations influence consumer and business decision making.",
    "Consumer confidence can affect consumption spending in the economy.",
    "Economic models simplify reality using assumptions and variables.",
    "Economics connects individual behavior with broader social outcomes."
    
]