DOMAIN_name = "biology"

TEXTS = [

     "Law is a system of rules that governs behavior in society.",
    "Legal systems define rights, duties, and obligations of individuals and institutions.",
    "The rule of law means everyone is subject to the law, including authorities.",
    "Laws are created through legislative processes and democratic institutions.",
    "Courts interpret laws and resolve disputes through legal procedures.",
    "Judicial decisions apply legal rules to specific cases and evidence.",
    "Constitutions establish fundamental principles and limits of government power.",
    "Statutory law refers to written laws enacted by legislatures.",
    "Regulations provide detailed rules created by authorized agencies.",
    "Legal certainty depends on clear and consistent interpretation of rules.",

    "Criminal law addresses actions considered offenses against the state.",
    "Civil law resolves disputes between individuals or private entities.",
    "Administrative law governs decisions and actions of public agencies.",
    "Legal responsibility defines accountability for harmful or unlawful actions.",
    "Due process protects fairness in legal procedures and court proceedings.",
    "Presumption of innocence requires proof before punishment is imposed.",
    "Evidence is used to support or challenge legal claims in court.",
    "Legal standards define thresholds for proof and decision making.",
    "Judges evaluate facts and apply legal reasoning to reach decisions.",
    "Legal remedies provide solutions such as compensation or injunctions.",

    "Contracts create legally enforceable agreements between parties.",
    "Contract law requires offer, acceptance, and consideration to form an agreement.",
    "Breach of contract occurs when one party fails to fulfill obligations.",
    "Property law governs ownership and transfer of assets and land.",
    "Ownership grants legal control over use and transfer of property.",
    "Tort law addresses civil wrongs that cause harm to others.",
    "Negligence involves failing to meet a reasonable standard of care.",
    "Liability determines who is responsible for harm or damages.",
    "Consumer protection law aims to prevent unfair business practices.",
    "Employment law regulates relationships between employers and workers.",

    "Human rights law protects dignity and fundamental freedoms of people.",
    "Equality before the law requires similar cases to be treated consistently.",
    "Legal discrimination laws restrict unfair treatment based on protected traits.",
    "International law governs relations and agreements between states.",
    "Treaties are formal agreements recognized in international law.",
    "Legal compliance means following laws, regulations, and obligations.",
    "Law enforcement agencies uphold laws and maintain public order.",
    "Legal sanctions discourage violations through penalties or restrictions.",
    "Precedent means prior court decisions can guide future rulings.",
    "Case law develops through judicial interpretation over time.",

    "Legal interpretation clarifies meaning of laws when language is unclear.",
    "Statutory interpretation considers text, purpose, and legal context.",
    "Legal reasoning uses logic to connect facts, rules, and conclusions.",
    "Judicial review checks whether laws comply with constitutional principles.",
    "Separation of powers divides authority among branches of government.",
    "Checks and balances prevent concentration of power in one institution.",
    "Legal reforms update laws to reflect social changes and new challenges.",
    "Public law regulates the relationship between the state and citizens.",
    "Private law regulates legal relationships between individuals or organizations.",
    "Law supports social stability by resolving conflicts through legal methods."

]