DOMAIN_name = "biology"

TEXTS = [

     "Functions relate inputs to outputs through defined rules.",
    "A linear function has a constant rate of change.",
    "The slope of a line represents change in y over change in x.",
    "The y-intercept is where a line crosses the y-axis.",
    "Quadratic functions produce parabolic graphs.",
    "A quadratic equation can have two, one, or zero real solutions.",
    "Factoring is a method to solve certain polynomial equations.",
    "The quadratic formula solves ax^2 + bx + c = 0.",
    "Polynomials are expressions made of variables and coefficients.",
    "Exponents represent repeated multiplication of a base.",

    "Scientific notation expresses very large or very small numbers.",
    "Logarithms are inverse operations of exponentiation.",
    "Logarithm rules simplify multiplication and division of numbers.",
    "Systems of equations represent multiple conditions simultaneously.",
    "Substitution and elimination solve systems of linear equations.",
    "Inequalities represent ranges of possible values.",
    "Absolute value measures distance from zero on a number line.",
    "Functions can be increasing, decreasing, or constant over intervals.",
    "Domain and range describe allowable inputs and resulting outputs.",
    "A function can be represented by equations, graphs, or tables.",

    "Trigonometry studies relationships between angles and side lengths.",
    "Sine, cosine, and tangent are ratios in right triangles.",
    "The Pythagorean theorem relates sides of a right triangle.",
    "Trigonometric identities express equivalences between trig functions.",
    "Radians measure angles based on circle radius.",
    "The unit circle defines trigonometric values for common angles.",
    "Vectors have magnitude and direction in coordinate geometry.",
    "Vector addition combines direction and magnitude of quantities.",
    "Matrices organize numbers in rows and columns.",
    "Matrix multiplication follows specific algebraic rules.",

    "Probability measures likelihood of an event occurring.",
    "Independent events do not affect each other’s outcomes.",
    "Dependent events affect probabilities of each other.",
    "Conditional probability measures probability given another event occurs.",
    "Random variables represent numerical outcomes of random processes.",
    "Expected value represents the long-term average outcome.",
    "Statistics summarizes and analyzes data using numerical measures.",
    "Mean, median, and mode describe central tendency of a dataset.",
    "Standard deviation measures spread of data around the mean.",
    "Correlation measures the strength of a relationship between variables.",

    "Sequences are ordered lists of numbers following a rule.",
    "Arithmetic sequences have a constant difference between terms.",
    "Geometric sequences have a constant ratio between terms.",
    "Series represent the sum of terms in a sequence.",
    "Limits describe values approached by functions near specific points.",
    "Derivatives measure instantaneous rate of change of a function.",
    "Integrals represent accumulation and area under a curve.",
    "Calculus connects derivatives and integrals through the fundamental theorem.",
    "Mathematical proofs justify statements using logical reasoning.",
    "Mathematics builds structured knowledge from axioms and definitions."
    
]