DOMAIN_name = "biology"

TEXTS = [

     "Medicine studies the prevention, diagnosis, and treatment of disease.",
    "Health is influenced by biological, environmental, and social factors.",
    "Disease occurs when normal body function is disrupted.",
    "Diagnosis identifies medical conditions using evidence and symptoms.",
    "Treatment aims to reduce symptoms and restore body function.",
    "Prevention reduces risk by avoiding causes or strengthening protection.",
    "Infectious diseases are caused by pathogens such as bacteria and viruses.",
    "Noninfectious diseases can involve genetics, lifestyle, or environment.",
    "The immune system protects the body by recognizing harmful agents.",
    "Inflammation is a protective response to injury or infection.",

    "Antibodies bind specific antigens as part of adaptive immunity.",
    "Vaccination triggers immune memory for faster future protection.",
    "Antibiotics target bacteria but do not work against viruses.",
    "Viruses replicate inside host cells using cellular machinery.",
    "Epidemiology studies patterns and causes of disease in populations.",
    "Transmission can occur through contact, droplets, or contaminated surfaces.",
    "Public health programs reduce disease spread through prevention strategies.",
    "Hygiene helps reduce exposure to infectious agents.",
    "Medical screening detects disease risk before symptoms appear.",
    "Risk factors increase the likelihood of illness or poor outcomes.",

    "Anatomy studies the structure of organs and body systems.",
    "Physiology studies how body systems function and maintain balance.",
    "Homeostasis regulates internal conditions like temperature and pH.",
    "The circulatory system delivers oxygen and nutrients to tissues.",
    "The respiratory system exchanges oxygen and carbon dioxide in the lungs.",
    "The nervous system coordinates body responses through electrical signals.",
    "The endocrine system regulates processes through hormones in the bloodstream.",
    "The digestive system breaks down food into absorbable nutrients.",
    "The kidneys filter blood and regulate water and salt balance.",
    "The musculoskeletal system enables movement and structural support.",

    "Medical imaging helps visualize internal organs and tissues.",
    "Laboratory tests measure biomarkers to support diagnosis.",
    "Clinical evidence supports decisions about treatments and outcomes.",
    "Evidence-based medicine uses research results to guide patient care.",
    "Side effects are unintended outcomes that may occur from treatments.",
    "Clinical trials evaluate safety and effectiveness of medical interventions.",
    "Dosage and administration influence the effectiveness of a treatment plan.",
    "Chronic diseases persist over time and require long-term management.",
    "Acute conditions develop quickly and may require urgent care.",
    "Mental health affects emotion, thinking, and daily functioning.",

    "Stress can influence immune function and overall well-being.",
    "Nutrition supports health through essential nutrients and energy balance.",
    "Exercise improves cardiovascular fitness and metabolic health.",
    "Medical ethics guides decisions about patient rights and safety.",
    "Confidentiality protects private health information in medical care.",
    "Healthcare systems organize resources to provide medical services.",
    "Access to care can affect health outcomes across populations.",
    "Patient safety reduces harm during diagnosis and treatment processes.",
    "Doctors and nurses coordinate care using clinical guidelines.",
    "Medicine combines scientific knowledge with compassionate care."
]