DOMAIN_name = "physics"

TEXTS = [

     "Newton's first law states that an object remains at rest or in motion unless acted on by a net force.",
    "Newton's second law relates force, mass, and acceleration through F = ma.",
    "Newton's third law states that forces come in equal and opposite pairs.",
    "Friction is a force that opposes motion between two surfaces in contact.",
    "Air resistance increases with speed and depends on an object's shape.",
    "Momentum is conserved in an isolated system during collisions.",
    "Impulse equals change in momentum and depends on force and time.",
    "Work is done when a force causes displacement in the direction of the force.",
    "Power is the rate at which work is done or energy is transferred.",
    "Kinetic energy depends on mass and the square of velocity.",

    "Gravitational potential energy depends on mass, gravity, and height.",
    "Mechanical energy is the sum of kinetic and potential energy in a system.",
    "Energy is conserved but can transform between different forms.",
    "Circular motion requires a centripetal force directed toward the center.",
    "Centripetal acceleration increases with speed and decreases with radius.",
    "Projectile motion can be analyzed using horizontal and vertical components.",
    "Velocity is a vector quantity with magnitude and direction.",
    "Acceleration measures the rate of change of velocity over time.",
    "A free-body diagram shows all forces acting on an object.",
    "Balanced forces result in constant velocity or no motion.",

    "Pressure is force per unit area and increases when area decreases.",
    "Density is mass per unit volume and affects buoyancy in fluids.",
    "Temperature is related to the average kinetic energy of particles.",
    "Heat transfer occurs through conduction, convection, or radiation.",
    "Thermal expansion occurs when materials increase in size with temperature.",
    "Phase changes involve energy transfer without changing temperature.",
    "Waves transfer energy without transferring matter over long distances.",
    "Wave speed equals frequency times wavelength.",
    "Sound waves require a medium and cannot travel through a vacuum.",
    "The Doppler effect changes perceived frequency due to relative motion.",

    "Light behaves as an electromagnetic wave with a constant speed in vacuum.",
    "Reflection follows the law that angle of incidence equals angle of reflection.",
    "Refraction occurs when light changes speed entering a new medium.",
    "Snell's law relates angles of incidence and refraction with refractive index.",
    "Lenses form images by bending light rays through refraction.",
    "The electromagnetic spectrum includes radio, microwave, infrared, and visible light.",
    "Electric charge can be positive or negative and is conserved.",
    "Coulomb's law describes the force between electric charges.",
    "Electric fields represent the force experienced by a test charge.",
    "Voltage represents electrical potential difference between two points.",

    "Current is the rate of flow of electric charge in a circuit.",
    "Ohm's law states that voltage equals current times resistance.",
    "Resistors convert electrical energy into heat energy in circuits.",
    "Series circuits have the same current through all components.",
    "Parallel circuits have the same voltage across each branch.",
    "Magnetic fields are produced by moving electric charges.",
    "Electromagnets use current to create a controllable magnetic field.",
    "Electromagnetic induction generates voltage from changing magnetic flux.",
    "Transformers change voltage levels using electromagnetic induction.",
    "Energy in circuits follows conservation principles and power relationships."
    
]